version: '3'
services:
  #deploy:
    #build: .
    #ports:
      #- "8000:8000"
    #command: sh -c "while true; do sleep 1; done"
    #volumes:
      #- .:/code
      #- ..:/app
  web:
    build: .
    ports:
      - "9000:8000"
    command:
      - /bin/bash
      - -c
      - |
        uvicorn deploy_api:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
      - ..:/app
